# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '0834XMPP' do
pod 'JDStatusBarNotification', '~> 1.5.2'
pod 'MBProgressHUD', '~> 0.9.1'
end

